# Site settings
title: QIA
description: official webpage of Quantum Intelligence Alliance
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Quantum Intelligence Alliance
user_description: innovation happens at the intersections
user_title: # subtitle
email: aritra.sarkar@quantum-intelligence.net
twitter_username: lorem_ipsum
github_username: Advanced-Research-Centre
# gplus_username:  lorem_ipsum

# Based on Aritra's website
url: 'https://quantum-intelligence.net'
baseurl: ''
favicon-32x32: 'favicon-32x32.png'

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src', 'node_modules']
